### ISSUE TITLE
Speed-up and/or reuse of fault ray tracing results

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/flownet#102]

**Comment by wouterjdb** [comment]
The current calculation of fault definitions in FlowNet, which ultimately uses the Møller-Trumbore algorithm, is described in the code as:

https://github.com/equinor/flownet/blob/8922a48109318856b4b5462fa3fe994a94c5d41f/src/flownet/network_model/_network_model.py#L238-L245

For smaller models, like Brugge, this was -albeit somewhat slow- fine enough. For larger models, with many faults and many nodes this method becomes extremely slow.

What happens is for _every_ triangle in _every_ fault, _every_ pair of nodes (vector) is tested for intersection. In a lot of cases we can know a priori that we cannot intersect because a fault (or triangle) is outside of the bounding box of a pair of nodes. If we would simply ignore all triangles outside of the bounding box we will reduce the number of times that the ray-tracing function is called significantly.

I suggest to implement this speed up and see if further speeds-up are still required.
