### ISSUE TITLE
Long connections across Norne separate regions to be removed

### ISSUE THREAD

**Issue by edubarrosTNO** [equinor/flownet#282]
While inspecting the grid of one of the FlowNet realizations of Norne, it was observed that extremely long connections are appearing between well nodes in the two "tentacles" of the model. A fixed maximum distance value should be used to determine connections to be removed instead of a fraction as it is currently set up

![image](https://user-images.githubusercontent.com/9119793/101170881-57465a00-363f-11eb-9448-d0cf51132bc7.png)

**Comment by wouterjdb** [comment]
Already supported!

https://github.com/equinor/flownet/blob/d81a3833a742a95bff96c7c487a66cd739b20b97/src/flownet/config_parser/_config_parser.py#L330

**Comment by wouterjdb** [comment]
I actually think that what is the problem is that we should remove connections that go through non-reservoir as just setting the max distance is not enough:

The distance over the tentacles is ~2400m; whereas the distance from the tentacle to the F-4H injector is ~2500m. That would mean that in this way of defining what needs to be removed there will never be communication between the injector and the producer in the tentacle.

A potential solution could be to recognize that part of the model is a completely different (disconnected) area and could be its own FlowNet? 🤔
