### ISSUE TITLE
Remove unused (non-production) connections in Norne wells

### ISSUE THREAD

**Issue by wouterjdb** [equinor/flownet#324]
In Norne there are for all wells some initial connections/perforations that are never produced. They can be removed (commented out) in the flownet/test-data repository.

**Comment by edubarrosTNO** [comment]
After running the CI tests on the test branch of PR #327, there seems to be issues with some of the wells not appearing properly in the generated `HISTORY_SCHEDULE.inc` file. For some reason (unknown at the moment), some of the wells appear only in the `COMPDAT` keyword, but are not referred to in the `WELSPECS` nor in the control keywords, causing OPM-Flow simulations to fail. After removing those wells and their respective `COMPDAT` keywords, the simulations went through.

Those wells were: `E-3AH, D-4AH, B-4BH, D-1CH, B-4DH, E-3CH, E-2AH, D-3BH, B-1BH, K-3H`. Next, I will try to find out what these wells have in common, but a closer look into the code will probably be necessary as well to get a full picture of what is happening. I could use some help here...

**Comment by edubarrosTNO** [comment]
It turns out that there was a problem with well `F-3H` in the schedule file of the new version of the Norne model uploaded in PR https://github.com/equinor/flownet-testdata/pull/36 which caused the reference simulation to be incomplete and the FlowNet generated `HISTORY_SCHEDULE.inc` file to be malformed for the wells identified above (all those supposed to appear after well `F-3H` in the schedule).

After fixing the problem with `F-3H` this new version model runs locally using the settings of https://github.com/equinor/flownet-testdata/blob/master/norne/config/assisted_history_matching.yml, while before all the realizations would fail. However, when using the CI settings the simulations for the 2 realizations fail. I suspect it has to do with too few additional nodes (`additional_flow_nodes: 2` in CI config, 100 in regular config settings) which lead to poor network geometry. See figure below for both network generated, from CI config and regular config respectively.

![FlowNet_CI_config_3D_View_DEPTH](https://user-images.githubusercontent.com/36161163/108417461-e8cd6d00-7227-11eb-9734-a835deba80a4.png)

![FlowNet_3D_View_DEPTH](https://user-images.githubusercontent.com/36161163/108417477-ee2ab780-7227-11eb-903e-91dfa6db6166.png)

**Comment by wouterjdb** [comment]
You could verify that running the CI locally - see what the error is. But yes, increasing the number of node seems like a sensible way to go. But for the CI to run fast it would be beneficial to keep the number as low as possible. Is 10 high enough?

**Comment by edubarrosTNO** [comment]
Yes, I re-ran the CI locally with `additional_flow_nodes: 10` and the simulations succeeded. Just pushed a new commit updating the CI config for Norne in PR equinor/flownet-testdata#36 and restarted the CI checks in PR #327. If all checks pass this time, equinor/flownet-testdata#36 will be ready for merging
