### ISSUE TITLE
Installation issue on server

### ISSUE THREAD

**Issue by Riccardopeli** [equinor/flownet#352]
I have installed FlowNet on a server, compiling OPM from source.
The Flownet installation seems to run smoothly.
However, when I run FlowNet, I get the following error, after the parameters initialization
![2021_03_08_0g6_Kleki](https://user-images.githubusercontent.com/18396660/110296730-f12cf280-7ff2-11eb-9e53-1bd4719ed17a.png)
In the ert-log.txt file, I see
![2021_03_08_0gg_Kleki](https://user-images.githubusercontent.com/18396660/110297991-56351800-7ff4-11eb-89bc-bff7f13d44a1.png)

Is that mean that the paths to libraries ecl and flow are not correctly set?
I am quite sure that the FLOW_PATH variable is correctly defined

**Comment by wouterjdb** [comment]
It might have something to do with the installation of the `_flow_job` having failed?

https://github.com/equinor/flownet/blob/ae1216ae95d6373b441d7b613ba42ab6109a4de2/setup.py#L61

**Comment by wouterjdb** [comment]
I would be surprised if flow version is the problem. I'm currently running 2020.10 though.

Have you looked at thelogs for individual realizations? Like the Flow runs themselves? Are they failing due to some simulation isssue? Or are you not getting there...?

**Comment by Riccardopeli** [comment]
I am not getting there. The folder output  is not created

**Comment by wouterjdb** [comment]
Any progress? There have been some newer releases of FlowNet, as well as a problem with a recent ERT release (#367). Not sure if anything has to do with it - but maybe a fresh start helps.

Given that that doesn't help and you end up in the same issue: As the ERT job has started you should have a folder with the ert configration file. You could run the ERT configuration manually using:

```bash
ert es_mda ahm_config.ert
```

You should get some more info on what is going wrong. Maybe that info helps in identifying where your issue is.

**Comment by Riccardopeli** [comment]
I got the point! 
The error is due to the queue variable in the ert section of the yaml file. Indeed from ert I get:
`Error message: queue_config_init: queue system :local not recognized `

What I do not understand is how to correctly setup the file. In particular, how should I set 
queue:
    system: ?
    name: ?
    server: ?

I'd like to run FlowNet through PBS job scheduling, but I don't find any example running Flownet, except on a LOCAL system.
Could you please provide me the instruction to setup the three parameters above?

Thanks

**Comment by olelod** [comment]
FlowNet is currently set up to run either locally or through an LSF queue system. ERT supports a few more, I see, among those TORQUE (a version of PBS). Is that the one you are using?

**Comment by Riccardopeli** [comment]
We use PBS Pro. Do you know if it is supported?

**Comment by wouterjdb** [comment]
I'm not entirely sure what is and what is not support. As this is more related to the internals of ERT, I suggest you post this question on https://github.com/equinor/ert.

**Comment by olelod** [comment]
So you use `qsub` to submit jobs? If so, you may be lucky, and just setting `system: TORQUE` in the config file will do. (you also need to set `name: something` and `server: something` since the LSF option would require them, but these values will not be used for anything. 

There are some other options to play with (ref https://joakim-hove.github.io/manual/keywords/index.html#configuring-torque-access), and those could be altered within the `src/flownet/templates/common_config.ert.jinja2` file somehow. I don't have any experience with this, and you would be more likely to succeed getting help on the ERT github pages as @wouterjdb suggests.

**Comment by Riccardopeli** [comment]
We solved the issue. It was due to the presence of `--` in the installation path (gnu--8.3), that was interpreted by Ert as a comment, preventing to set the correct paths.

Thank you for your time

**Comment by wouterjdb** [comment]
Thanks for letting us know. I'll close the issue then.
