### ISSUE TITLE
Change name "Eclipse" to "OPM Flow"

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/flownet#37]
Author: @wouterjdb 

We aim at using Flow - but we still call the simulator "Eclipse" in many places.

**Comment by olwijn** [comment]
The usage of "Eclipse" in the code is mostly restricted to functionality to read from ECLIPSE-formatted simulation output (at this moment actually ECLIPSE simulations). In most other cases it appears in comments in combinations such as "Eclipse/Flow", or clearly refers to a required formatting that follows the 'Eclipse conventions'. In my view such usages are appropriate. 

I think replacement of "eclipse" by "flow" is warranted for example in the name of the file location where simulation results appear, since these will be obtained by running Flow. The following code lines were identified where changes shold perhaps be made:

src/flownet/config_parser/_config_parser.py 32
src/flownet/config_parser/_config_parser.py 417
src/flownet/config_parser/_config_parser_pred.py 82
src/flownet/network_model/_generate_connections.py 317, 440, 448 (comment)
src/flownet/realization/_render_realization.py 20 (comment)
src/flownet/templates/common_config.ert.jinja2 29, 31-34
